CREATE TABLE tblRevendedor
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Sobrenome VARCHAR(50) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	Email VARCHAR(300) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	AprovAuto BIT NOT NULL DEFAULT(0),
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE UNIQUE INDEX IDX_CPF_UNIQUE ON tblRevendedor(CPF)
GO

CREATE TABLE tblPedido
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IdRevendedor INT NOT NULL,
	IdProduto INT NOT NULL,
	IdStatus SMALLINT NOT NULL DEFAULT(1),
	Quantidade SMALLINT NOT NULL,
	Valor DECIMAL(15,4) NOT NULL,
	Data DATETIME NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE TABLE tblStatus
(
	Id INT NOT NULL PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

INSERT INTO tblStatus VALUES (1,'Em Validação', GETDATE());
INSERT INTO tblStatus VALUES (2,'Aprovado', GETDATE());
INSERT INTO tblStatus VALUES (3, 'Reprovado', GETDATE());
GO

CREATE TABLE tblProduto
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IdCategoria INT NOT NULL,
	Codigo VARCHAR(10) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Valor DECIMAL(15,4) NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE TABLE tblCategoria
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE TABLE tblSoftPlanConfig
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ValorDe DECIMAL(15,4) NOT NULL,
	ValorAte DECIMAL(15,4) NOT NULL,
	Porcentagem DECIMAL(15,4) NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE TABLE tblSoftPlanConfigCategoria
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IdCategoria INT NOT NULL,
	IdSoftPlan INT NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO

CREATE UNIQUE INDEX IDX_CashbakCategoria ON tblCashbakSoftPlanConfig(IdCategoria, IdSoftPlan);
GO

CREATE TABLE tblRevendedorSoftPlan
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	IdPedido INT NOT NULL,
	IdSoftPlanConfig INT NOT NULL,
	Valor DECIMAL(15,4) NOT NULL,
	DataCadastro DATETIME NOT NULL DEFAULT(GETDATE())
)
GO